server:
  port: 8080

spring:
  profiles:
    active: development

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    cors:
      allowed-origins: https://kma-legend.onrender.com

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://monorail.proxy.rlwy.net:55842/codewalker}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:viCcTTMFvChjFidsLYaBdRIpEubzzCFC}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

api:
  prefix: api/v1

#server:
#  port: 8080
#
#spring:
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#  mvc:
#    cors:
#      allowed-origins: http://localhost:4200
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:4306/codewalker}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${SPRING_DATASOURCE_USERNAME:root}
#    password: ${SPRING_DATASOURCE_PASSWORD:123456789}
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#
#api:
#  prefix: api/v1

#server:
#  port: 8080
#
#spring:
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#  mvc:
#    cors:
#      allowed-origins: http://localhost:4200
#  datasource:
#    url: jdbc:sqlserver://kmalegend.database.windows.net:1433;database=kmalegend;user=codewalker@kmalegend;password={Haibeo2004@};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: codewalker
#    password: Haibeo2004@
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#
#api:
#  prefix: api/v1